name: Build & Push core-spring-service to ECR

on:
  workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Build Spring Boot JAR
        working-directory: ./core-spring-service
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t core-spring-service ./core-spring-service

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-easy-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to ECR
        run: |
          docker tag core-spring-service:latest ${{ steps.login-ecr.outputs.registry }}/core-spring-service-up:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/core-spring-service-up:latest
